In [1]:
# importing pandas for dataframe
import pandas as pd

In [2]:
# df-->dataframe
df = pd.read_csv(r"C:\Users\A.JANAKIRAMAN\Downloads\3.1-data-sheet-guvi-courses.csv")
df

course_id                                       course_title  \
0       41295.0               Learn HTML5 Programming From Scratch   
1       59014.0                     Coding for Entrepreneurs Basic   
2      625204.0                         The Web Developer Bootcamp   
3      173548.0  Build Your First Website in 1 Week with HTML5 ...   
4      764164.0              The Complete Web Developer Course 2.0   
...         ...                                                ...   
3675  1216340.0                  Learn to Play Sweet Child of Mine   
3676  1026762.0  Coaching Course: Rhythm Instruction for Music ...   
3677  1223240.0  Learn Pirates of the Caribbean by Ear on the P...   
3678  1224186.0  Learn to Play Piano Like a Pro - Easy Piano Co...   
3679  1234656.0                              4 Week Rhythm Mastery   

                                                    url  price  \
0     https://www.udemy.com/learn-html5-programming-...    0.0   
1     https://www.udemy.com/coding-for-entrepreneurs...    0.0   
2     https://www.udemy.com/the-web-developer-bootcamp/  200.0   
3     https://www.udemy.com/build-your-first-website...    0.0   
4     https://www.udemy.com/the-complete-web-develop...  200.0   
...                                                 ...    ...   
3675  https://www.udemy.com/learn-to-play-sweet-chil...   20.0   
3676  https://www.udemy.com/coaching-bundle-rhythm-i...  125.0   
3677  https://www.udemy.com/learn-pirates-of-the-car...   20.0   
3678  https://www.udemy.com/learn-to-play-piano-like...   35.0   
3679       https://www.udemy.com/4-week-rhythm-mastery/   20.0   

      num_subscribers  num_reviews  num_lectures           level  Rating  \
0            268923.0       8629.0          45.0  Beginner Level    0.82   
1            161029.0        279.0          27.0    Expert Level    0.69   
2            121584.0      27445.0         342.0  Beginner Level    0.89   
3            120291.0       5924.0          30.0      All Levels    0.78   
4            114512.0      22412.0         304.0  Beginner Level    0.55   
...               ...          ...           ...             ...     ...   
3675              0.0          0.0          23.0      All Levels    0.31   
3676              0.0          0.0           7.0  Beginner Level    0.06   
3677              0.0          0.0           6.0      All Levels    0.08   
3678              0.0          0.0          13.0  Beginner Level    0.78   
3679              0.0          0.0          28.0      All Levels    0.01   

      content_duration   published_timestamp                   subject  
0            10.500000  2013-02-14T07:03:41Z  Subject: Web Development  
1             3.500000  2013-06-09T15:51:55Z  Subject: Web Development  
2            43.000000  2015-11-02T21:13:27Z  Subject: Web Development  
3             3.000000  2014-04-08T16:21:30Z  Subject: Web Development  
4            30.500000  2016-03-08T22:28:36Z  Subject: Web Development  
...                ...                   ...                       ...  
3675          1.500000  2017-06-30T17:33:29Z       Musical Instruments  
3676          0.633333  2017-03-10T17:06:46Z       Musical Instruments  
3677          0.533333  2017-05-22T17:14:43Z       Musical Instruments  
3678          0.516667  2017-05-30T00:19:02Z       Musical Instruments  
3679          2.500000  2017-07-05T16:07:44Z       Musical Instruments  

[3680 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3680 entries, 0 to 3679
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object 
 2   url                  3676 non-null   object 
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object 
 8   Rating               3676 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   object 
 11  subject              3677 non-null   object 
dtypes: float64(7), object(5)
memory usage: 345.1+ KB


In [4]:
df.isnull().sum()

course_id              4
course_title           4
url                    4
price                  4
num_subscribers        4
num_reviews            4
num_lectures           4
level                  4
Rating                 4
content_duration       4
published_timestamp    4
subject                3
dtype: int64

In [5]:
df.dropna(inplace=True)
df.isnull().sum()

course_id              0
course_title           0
url                    0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
Rating                 0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3676 entries, 0 to 3679
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object 
 2   url                  3676 non-null   object 
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object 
 8   Rating               3676 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   object 
 11  subject              3676 non-null   object 
dtypes: float64(7), object(5)
memory usage: 373.3+ KB


In [7]:
df.set_index(['course_id','course_title','url'], inplace = True)
df

price  \
course_id course_title                                       url                                                         
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...    0.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...    0.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/   200.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...    0.0   
764164.0  The Complete Web Developer Course 2.0              https://www.udemy.com/the-complete-web-develope...  200.0   
...                                                                                                                ...   
1216340.0 Learn to Play Sweet Child of Mine                  https://www.udemy.com/learn-to-play-sweet-child...   20.0   
1026762.0 Coaching Course: Rhythm Instruction for Music E... https://www.udemy.com/coaching-bundle-rhythm-in...  125.0   
1223240.0 Learn Pirates of the Caribbean by Ear on the Piano https://www.udemy.com/learn-pirates-of-the-cari...   20.0   
1224186.0 Learn to Play Piano Like a Pro - Easy Piano Cou... https://www.udemy.com/learn-to-play-piano-like-...   35.0   
1234656.0 4 Week Rhythm Mastery                              https://www.udemy.com/4-week-rhythm-mastery/         20.0   

                                                                                                                 num_subscribers  \
course_id course_title                                       url                                                                   
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...         268923.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...         161029.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/          121584.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...         120291.0   
764164.0  The Complete Web Developer Course 2.0              https://www.udemy.com/the-complete-web-develope...         114512.0   
...                                                                                                                          ...   
1216340.0 Learn to Play Sweet Child of Mine                  https://www.udemy.com/learn-to-play-sweet-child...              0.0   
1026762.0 Coaching Course: Rhythm Instruction for Music E... https://www.udemy.com/coaching-bundle-rhythm-in...              0.0   
1223240.0 Learn Pirates of the Caribbean by Ear on the Piano https://www.udemy.com/learn-pirates-of-the-cari...              0.0   
1224186.0 Learn to Play Piano Like a Pro - Easy Piano Cou... https://www.udemy.com/learn-to-play-piano-like-...              0.0   
1234656.0 4 Week Rhythm Mastery                              https://www.udemy.com/4-week-rhythm-mastery/                    0.0   

                                                                                                                 num_reviews  \
course_id course_title                                       url                                                               
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...       8629.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...        279.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/       27445.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...       5924.0   
764164.0  The Complete Web Developer Cour

In [8]:
df['subject'].unique()

array(['Subject: Web Development', 'Business Finance', 'Graphic Design',
       'Musical Instruments'], dtype=object)

In [9]:
from sklearn.preprocessing import OrdinalEncoder
eng = OrdinalEncoder()
df['subject'] = eng.fit_transform(df[['subject']])

In [10]:
df['subject'].unique()

array([3., 0., 1., 2.])

In [11]:
df['level'].unique()

array(['Beginner Level', 'Expert Level', 'All Levels',
       'Intermediate Level'], dtype=object)

In [12]:
df['level'] = eng.fit_transform(df[['level']])

In [13]:
df['level'].unique()

array([1., 2., 0., 3.])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3676 entries, (41295.0, 'Learn HTML5 Programming From Scratch', 'https://www.udemy.com/learn-html5-programming-from-scratch/') to (1234656.0, '4 Week Rhythm Mastery', 'https://www.udemy.com/4-week-rhythm-mastery/')
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   price                3676 non-null   float64
 1   num_subscribers      3676 non-null   float64
 2   num_reviews          3676 non-null   float64
 3   num_lectures         3676 non-null   float64
 4   level                3676 non-null   float64
 5   Rating               3676 non-null   float64
 6   content_duration     3676 non-null   float64
 7   published_timestamp  3676 non-null   object 
 8   subject              3676 non-null   float64
dtypes: float64(8), object(1)
memory usage: 753.3+ KB


In [15]:
df.drop_duplicates()

price  \
course_id course_title                                       url                                                         
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...    0.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...    0.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/   200.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...    0.0   
764164.0  The Complete Web Developer Course 2.0              https://www.udemy.com/the-complete-web-develope...  200.0   
...                                                                                                                ...   
1216340.0 Learn to Play Sweet Child of Mine                  https://www.udemy.com/learn-to-play-sweet-child...   20.0   
1026762.0 Coaching Course: Rhythm Instruction for Music E... https://www.udemy.com/coaching-bundle-rhythm-in...  125.0   
1223240.0 Learn Pirates of the Caribbean by Ear on the Piano https://www.udemy.com/learn-pirates-of-the-cari...   20.0   
1224186.0 Learn to Play Piano Like a Pro - Easy Piano Cou... https://www.udemy.com/learn-to-play-piano-like-...   35.0   
1234656.0 4 Week Rhythm Mastery                              https://www.udemy.com/4-week-rhythm-mastery/         20.0   

                                                                                                                 num_subscribers  \
course_id course_title                                       url                                                                   
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...         268923.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...         161029.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/          121584.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...         120291.0   
764164.0  The Complete Web Developer Course 2.0              https://www.udemy.com/the-complete-web-develope...         114512.0   
...                                                                                                                          ...   
1216340.0 Learn to Play Sweet Child of Mine                  https://www.udemy.com/learn-to-play-sweet-child...              0.0   
1026762.0 Coaching Course: Rhythm Instruction for Music E... https://www.udemy.com/coaching-bundle-rhythm-in...              0.0   
1223240.0 Learn Pirates of the Caribbean by Ear on the Piano https://www.udemy.com/learn-pirates-of-the-cari...              0.0   
1224186.0 Learn to Play Piano Like a Pro - Easy Piano Cou... https://www.udemy.com/learn-to-play-piano-like-...              0.0   
1234656.0 4 Week Rhythm Mastery                              https://www.udemy.com/4-week-rhythm-mastery/                    0.0   

                                                                                                                 num_reviews  \
course_id course_title                                       url                                                               
41295.0   Learn HTML5 Programming From Scratch               https://www.udemy.com/learn-html5-programming-f...       8629.0   
59014.0   Coding for Entrepreneurs Basic                     https://www.udemy.com/coding-for-entrepreneurs-...        279.0   
625204.0  The Web Developer Bootcamp                         https://www.udemy.com/the-web-developer-bootcamp/       27445.0   
173548.0  Build Your First Website in 1 Week with HTML5 a... https://www.udemy.com/build-your-first-website-...       5924.0   
764164.0  The Complete Web Developer Cour

In [16]:
df.to_csv('cleaned guvi data.csv', index=False)

In [17]:
y  = df['Rating']
x = df.drop(['Rating','published_timestamp'],axis = 1)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.15)

In [19]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3124, 7), (552, 7), (3124,), (552,))

In [20]:
# sample algorithm for reference
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
result = model.fit(x_train, y_train)

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Assuming you have your model and predictions
y_pred = result.predict(x_test)

# Calculate the Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)

# Calculate the Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)

# Calculate the R-squared (R2)
r2 = r2_score(y_test, y_pred)

print('Mean Squared Error (MSE):', mse)
print('Root Mean Squared Error (RMSE):', rmse)
print('R-squared (R2):', r2)

Mean Squared Error (MSE): 0.10617422000805153
Root Mean Squared Error (RMSE): 0.3258438583248908
R-squared (R2): 0.006760791397175225


In [22]:
prid_data = np.array([[0.0,262600.0,8000.0,20.0,1.0,10.5,3.0]])
# given_predict = result.predict(prid_data)
given_predict1 = result.predict(prid_data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [23]:
# print(given_predict)
given_predict1

array([0.82])

In [24]:
import pickle
pickle.dump(result,open('Trained_guvi.pkl','wb'))

In [25]:
load_mod = pickle.load(open(r"C:\Users\A.JANAKIRAMAN\Trained_guvi.pkl",'rb'))

In [26]:
prid_data = np.array([[0.0,262600.0,8000.0,20.0,1.0,10.5,3.0]])
# given_predict = result.predict(prid_data)
given_predict = load_mod.predict(prid_data)
given_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([0.82])

In [27]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor,
                              ExtraTreesRegressor, HistGradientBoostingRegressor)
from sklearn.svm import SVR
reg_algo = {'DecisionTreeRegressor': DecisionTreeRegressor,
            'RandomForestRegressor': RandomForestRegressor,
            'AdaBoostRegressor': AdaBoostRegressor,
            'GradientBoostingRegressor': GradientBoostingRegressor,
            'ExtraTreesRegressor': ExtraTreesRegressor,
            'HistGradientBoostingRegressor':HistGradientBoostingRegressor,
            'SVR': SVR}
for key, value in reg_algo.items():
    model = value()
    result = model.fit(x_train, y_train)
    pickle.dump(result,open(key +'.sav','wb'))
    
    
    

In [28]:
! pip install --upgrade scikit-learn 

SyntaxError: invalid syntax (3375514906.py, line 1)

In [30]:
import sklearn
print(sklearn.__version__)

1.3.2
